name: CI for Java
on:
  push:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:
jobs:
  set_env:
    runs-on: ubuntu-latest

    steps:

    - name: Set up JDK '17'
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: zulu

    - name: Checkout
      uses: actions/checkout@v4.1.3

    - name: Install dependencies
      run: mvn clean install

    - name: Build app
      run: mvn package -DskipTests

    - name: Run Test
      run: mvn test
